import esbuild from "esbuild";

await esbuild.build({
  entryPoints: ["src/main.js"],
  bundle: true,
  external: ["obsidian", "electron"],
  format: "cjs",
  target: "es2020",
  platform: "browser",
  minify: false,
  sourcemap: false,
  banner: {
    js: "/*\nTHIS FILE IS BUILT (esbuild) FROM src/main.js + the vendored modern-screenshot\ncapture library. It is intentionally NOT minified so it stays readable and\ndebuggable directly in Obsidian's dev console.\n\nDo not edit this file by hand -- edit src/main.js and run `npm run build`.\n*/",
  },
  outfile: "dist/main.js",
});
console.log("build ok -> dist/main.js");
